# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Cypress run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-test:
    name: Run on Chrome 83
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.0-chrome83-ff77
    steps:
    - uses: actions/checkout@v2
    
    - name: Install cypress and verify
      run:
          npm ci
          $(npm bin)/cypress verify
          
    - name: Run cypress tests
      run: npm run test:chrome
    
    - name: Copy test execution videos and screeshots
      run:
        mkdir public &&
        cp -r cypress/videos public/videos &&
        cp -r cypress/screenshots public/screeshots
        
    - name: Merge test reports
      run: npm run test:merge-report
      
    - name: Generate HTML report
      run: npm run test:html-report
      
    - name: Deploy report page to github
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
